# Generated by Django 4.2.7 on 2023-11-28 06:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("E_Mart", "0003_tag_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="information",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
