# Generated by Django 4.2.7 on 2023-11-30 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("E_Mart", "0007_order_paid_order_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="E_Mart.order"
            ),
        ),
    ]
