# Generated by Django 4.2.7 on 2023-11-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("E_Mart", "0008_alter_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="postcode",
            field=models.IntegerField(null=True),
        ),
    ]
