# Generated by Django 4.2.7 on 2023-11-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("E_Mart", "0009_order_phone_alter_order_postcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="lastname",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
